# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Test Project' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Test Project
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'NSObject+Rx'
  pod 'RxAlamofire'

  target 'Test ProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Test ProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
